version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assuming the name is Dockerfile
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Assuming the Dockerfile name is Docker.dev
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
